# eu-west-1 --> ami-6f587e1c as ec2_image
# aws_region: 'eu-west-1'
# eu-central-1 --> ami-fe408091 as ec2_image
# aws_region: 'eu-central-1'
# us-west-2 --> ami-b7a114d7 as ec2_image
aws_region: 'us-west-2'
#  prefix for naming
aws_prefix: "cd"
#aws_vars_file: '{{aws_prefix}}_info'
aws_vars_file: '/tmp/{{aws_prefix}}_info'
#  availability zones
aws_az0: '{{ aws_region }}a'
aws_az1: '{{ aws_region }}b'
aws_az2: '{{ aws_region }}c'
# Default cidr block for vpc
# aws_vpc: "10.0.0.0/16"
# subnets
all_nets: "0.0.0.0/0"
# aws_subnet: "10.0.1.0/24"
ec2_sg_0: "sg-a17784c4"
ec2_sg_1: "sg-6da3770a"
ec2_sg_2: "sg-418bdb27"
# us-west-2 --> subnet-184aa67d as ec2_subnet
ec2_subnet: "subnet-184aa67d"
# ec2_node_number: 1
ec2_keypair: "cd-jenkins"
ec2_instance_type: "g2.2xlarge"
ec2_image: "ami-b7a114d7"
ec2_tag_Name: "jenkins-master-20170112"
ec2_tag_Type: "CICD"
# ec2_tag_Environment: "CICD"
ec2_root_disk_size: 20
# ec2_swap_size: 8
ec2_data_disk_size: 40
