---
  - hosts: jenkins-master
    user: ubuntu
    become: yes
    become_user: root
    gather_facts: True
    vars:
        jenkins_master_url: http://ec2-54-200-65-148.us-west-2.compute.amazonaws.com:8080
        jenkins_slave_secret: 6d62ea4f2d65d15c6e77ae49a892fa5af60ab865c75f44ce27c12ac382b71ad0
        jenkins_slave_nodename: local-slave
        jenkins_url_from_env: "{{ lookup('env','JENKINS_URL') }}"
    roles:
        - jenkins-slave
