---
    - name: Add Jenkins user
      user:
        name: jenkins
        group: docker

    - name: Download slave.jar
      get_url:
        url: "{{ jenkins_master_url }}/jnlpJars/slave.jar"
        dest: /home/jenkins/slave.jar
        mode: 0755
        owner: jenkins

    - name: run jenkins slave
      become: yes
      become_user: jenkins
    #   shell: "nohup java -jar slave.jar -jnlpUrl {{ jenkins_url_from_env }}/computer/ec2-slave/slave-agent.jnlp -secret {% if slave_secret|length > 0 %}{{ slave_secret }}{% else %}jenkins_slave_secret{% endif %} </dev/null >/dev/null 2>&1 &"
      shell: "java -jar /home/jenkins/slave.jar -jnlpUrl {{ jenkins_master_url }}/computer/{{ jenkins_slave_nodename }}/slave-agent.jnlp -secret {% if slave_secret is defined and slave_secret|length > 0 %}{{ slave_secret }}{% else %}{{ jenkins_slave_secret }}{% endif %} >> /home/jenkins/slave.log 2>&1 &"
