---
- include_vars: docker_vars.yml

#- name: Add Docker repository
#  yum_repository:
#    name: "docker"
#    description: "docker"
#    baseurl: "{{ baseurl }}"
#    enabled: yes
#    gpgcheck: yes
#   gpgkey: "{{ gpgkey }}"
#    state: present

- name: Install Docker
  yum:
    update_cache: yes
    name: "{{ package_name }}" 
    state: present

- name: Ensure that Docker service is running
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

#- name: Download Nvidia-docker rpm
#  get_url:
#    url: "{{ source_nvidia_docker }}"
#    dest: /tmp/
- name: Download ant unarchive nvidia-docker
  unarchive:
    remote_src: yes
    src: "{{ source_nvidia_docker }}"
    dst: "/usr/bin"
    extra_opts: "--strip-components=1"



