---
- include_vars: docker_vars.yml

- name: Install Docker
  yum:
    update_cache: yes
    name: "{{ package_name }}"
    state: present

- name: Ensure that Docker service is running
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Download and unarchive nvidia-docker
  unarchive:
    remote_src: yes
    src: "{{ source_nvidia_docker }}"
    dest: "/usr/bin"
    extra_opts: "--strip-components=1"
- name: Run nvidia-docker-plugin
  command: sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log

- name: Copy docker config options
  template:
    src: docker-storage.j2
    dest: /etc/sysconfig/docker-storage
  notify:
    - reload docker
  when: ansible_os_family == "RedHat"
