---
- include_vars: package_vars.yml

- name: install cmake and cmake3
  yum:
     name: "{{ item }}"
     enablerepo: epel
     state: present
  with_items: "{{ packages.cmake }}"

- name: add SCL repositories
  command: rpm -Uvh {{ item }}
  state: present
  with_items: "{{ packages.repositories }}"

- name: install gcc
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.gcc }}"

- name: Download newest NVIDIA driver
  get_url:
    url: "{{ packages[' nvidia_driver']['url'] }}"
    dest: /tmp/nvidia_driver

- name: Update NVIDIA driver
  shell: /tmp/NVIDIA-Linux-x86_64*.run -s 
