---
- name: Create swap file
  command: fallocate -l {{ swapsize }} /swapfile{{ swapsize }} creates=/swapfile{{ swapsize }}

- name: Change swap file permissions
  file: path=/swapfile{{ swapsize }} owner=root group=root mode=0600

- name: Format swap file
  command: mkswap /swapfile{{ swapsize }}

- name: mount swap volume
  command: swapon /swapfile{{ swapsize }}

- name: update fstab
  mount: name=none src=/swapfile{{ swapsize }} fstype=swap opts=defaults state=present
