---
- include_vars: swap_vars.yml
- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }}
  creates: "{{ swap_file_path }}"

- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600

- name: Make swap file
  command: "mkswap {{ swap_file_path }}"

- name: Mount swap
  command: "swapon {{ swap_file_path }}"

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    sysctl_set: yes
  
- name: Set cache
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ cache_value }}"
    sysctl_set: yes
  
=======
- name: Create swap file
  command: "fallocate -l {{ swapsize }} {{ swap_file }}{{ swapsize }} creates={{ swap_file }}{{ swapsize }}"

- name: Change swap file permissions
  file:
    path: "{{ swap_file }}{{ swapsize }}"
    owner: root
    group: root
    mode: 0600

- name: Format swap file
  command: "mkswap {{ swap_file }}{{ swapsize }}"

- name: mount swap volume
  command: "swapon {{ swap_file }}{{ swapsize }}"

- name: update fstab
  mount:
    name: none
    src: "{{ swap_file }}{{ swapsize }}"
    fstype: swap
    opts: defaults
    state: present

- name: Set sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    reload: no
    sysctl_set: yes
  with_dict: "{{ sysctl_params }}"
>>>>>>> ddd466c37c3201ece082743a0d3480336157ec9f
